[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
dotenvy = "0.15.7"
nom = "7.1.3"
num = "0.4.1"
prettytable-rs = "0.10.0"
